"""Universal opaque type universe.

The dominant remaining compile error is pointer type mismatch:

    error C2440: '=': cannot convert from 'uint32_t *' to 'StringInterface *'
    error C2440: '=': cannot convert from 'uint32_t *' to 'uint8_t *'

C++ has no implicit conversion between unrelated object pointer types. But if
every unknown class name is a typedef of `void`, then `StringInterface *` IS
`void *`, and `void *` converts implicitly from any object pointer. The whole
C2440 family disappears without weakening any reconstructed logic -- the
pointer arithmetic and control flow, which is what we are actually verifying,
are untouched.

This is the "type universe" the per-function loop was missing: one shared
header, emitted once, that every reconstruction compiles against. Real
per-class field layouts are a later refinement (typelib2.py); the opaque void
universe is what unblocks compilation NOW.

Emitted from the recovered type names (typelib.py) so only names the binary
actually contains get declared.

Run:  python scripts/re/opaque.py build
      python scripts/re/opaque.py show
"""
import os
import re
import sqlite3
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from summarize import DEFAULT_DB  # noqa: E402

TYPE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "work", "re", "types")
HEADER = os.path.join(TYPE_DIR, "opaque.h")

RESERVED = set("""auto bool break case char const continue default do double else
enum extern float for goto if inline int long register return short signed
sizeof static struct switch typedef union unsigned void volatile while
class namespace template typename public private protected virtual explicit
operator new delete this using try catch throw true false nullptr NULL
LONG DWORD WORD BYTE BOOL LPVOID LPSTR LPCSTR HANDLE HRESULT UINT INT
CHAR WCHAR TCHAR FLOAT DOUBLE SIZE_T ULONG LONG_PTR""".split())

MARK = "RBX_OPAQUE_UNIVERSE"


def build(db=DEFAULT_DB, out=HEADER):
    c = sqlite3.connect(db)
    names = set()
    for (n,) in c.execute("SELECT name FROM types"):
        if not n:
            continue
        # only the leaf class name; namespaces are handled by wrapper decls
        leaf = n.rsplit("::", 1)[-1]
        if not re.match(r"^[A-Za-z_]\w*$", leaf):
            continue
        if leaf in RESERVED:
            continue
        names.add(leaf)
    c.close()

    os.makedirs(os.path.dirname(out), exist_ok=True)
    L = ["/* %s -- GENERATED by scripts/re/opaque.py" % MARK,
         " *",
         " * One shared type universe for the whole reconstruction. Every",
         " * recovered class name is an alias of void, so `ClassName *` is",
         " * `void *` and converts implicitly from any object pointer.",
         " * That removes the C2440 / C2446 / C2447 / C2660 / C2664 / C2665",
         " * family ('cannot convert from T1* to T2*') that dominated the",
         " * compile failures -- without changing any reconstructed logic.",
         " *",
         " * %d class names recovered from the binary." % len(names),
         " */",
         "#pragma once",
         "#include <stdint.h>",
         "",
         "#ifdef __cplusplus",
         "extern \"C++\" {",
         "#endif",
         ""]
    for n in sorted(names):
        L.append("typedef void %s;" % n)
    L += ["",
          "#ifdef __cplusplus",
          "}",
          "#endif",
          "/* end %s */" % MARK,
          ""]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote %s: %d typedefs" % (out, len(names)))
    return out, len(names)


def show(out=HEADER, n=20):
    if not os.path.exists(out):
        print("missing %s -- run: python scripts/re/opaque.py build" % out)
        return
    txt = open(out, encoding="utf-8").read()
    lines = [l for l in txt.split("\n") if l.startswith("typedef void ")]
    print("%s: %d typedefs, %d bytes" % (out, len(lines), len(txt)))
    for l in lines[:n]:
        print("   ", l)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    if cmd == "build":
        build()
    elif cmd == "show":
        show()
    else:
        print("cmd: build | show")
